# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :betaLane do
    # add actions here: https://docs.fastlane.tools/actions
    
     build_app(
      workspace: "SignIn.xcworkspace",
      scheme: "SignIn",
      export_method: "app-store",
      clean: true,
      archive_path: ENV['ARCHIVE_PATH'],
      output_directory: ENV['OUTPUT_PATH'],
      sdk: "iphoneos",
      export_options: {
	"signingStyle": "manual",
	"provisioningProfiles": {
		"com.spanenterprises.SPANActivity": "SPANact Live Profile"
	}
      }
    )

    api_key = app_store_connect_api_key(
 	key_id: ENV['APP_STORE_CONNECT_API_KEY_ID'],
 	issuer_id: ENV['APP_STORE_CONNECT_API_ISSUER_ID'],
 	key_content: ENV['APP_STORE_CONNECT_API_KEY_CONTENT']
    )

    upload_to_testflight(
	skip_submission: true,
	username: ENV['APP_STORE_CONNECT_USERNAME'],
	apple_id: ENV['APPLE_ID_UNI']
    )

    pilot(
  	api_key: api_key,
	ipa: ENV['APP_PATH'],
	app_identifier: ENV['PILOT_APP_IDENTIFIER'],
	itc_provider:ENV['ITC_TEAM_ID']
    )
  end
end
