name: iOS Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Ruby and Fastlane
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.x

    - name: Install CocoaPods
      run: |
        gem install cocoapods
        gem install fastlane
        pod install --project-directory=SignIn/

    - name: Update provisioning profile specifier
      run: |
        gem install xcodeproj
        ruby - <<EOF
        require 'xcodeproj'
        project = Xcodeproj::Project.open('SignIn/SignIn.xcodeproj')
        target = project.targets.find { |t| t.name == 'SignIn' }
        target.build_configuration_list.build_configurations.each do |configuration|
          configuration.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = 'DemoTest'
        end
        project.save
        EOF

    - name: Build and Archive
      run: |
        cd SignIn/
        fastlane beta
